// GENERATED by scripts/generate-brand-components.mjs — do not edit by hand.
// Accent colours reference --color-league-accent, which falls back to the
// product accent, so this renders correctly inside and outside a league.
import { useId } from "react";

interface Props {
  className?: string;
  title?: string;
}

export default function DraftHQWordmark({ className = "h-24 w-auto", title = "DraftHQ" }: Props) {
  const uid = useId().replace(/:/g, "");
  return (
    <svg className={className} role="img" aria-label={title} id={`${uid}-Layer_1`} xmlns="http://www.w3.org/2000/svg" viewBox="108 155.3 984.1 193.4">
      <defs>
        <linearGradient id={`${uid}-linear-gradient`} x1="833.6" y1="156.17" x2="833.6" y2="335.26" gradientUnits="userSpaceOnUse">
          <stop offset="0" stopColor="var(--color-league-accent)"/>
          <stop offset="1" stopColor="var(--color-league-accent-border)"/>
        </linearGradient>
        <linearGradient id={`${uid}-linear-gradient-2`} x1="1007.54" y1="156.17" x2="1007.54" y2="335.26" href={`#${uid}-linear-gradient`}/>
      </defs>
      <g>
        <path d="m239.1,159.26h-95.83l-35.3,169.06h99.32c21.45,0,39.96-15.05,44.34-36.04l19.54-93.56c4.25-20.35-11.29-39.46-32.07-39.46Zm-7.52,48.12l-15.29,73.22c-1.65,7.88-8.6,13.53-16.66,13.53h-46.09l21.12-101.17h45.2c7.6,0,13.27,6.98,11.72,14.41Z" fill="#fff"/>
        <path d="m589.92,195.24l-1.26,6.04h35.67l-6.58,31.5h-35.66l-19.95,95.54h-36.99l19.95-95.54h-17l6.57-31.5h17l3.22-15.42h0c3.72-17.83,19.44-30.61,37.65-30.61h42.37l-6.39,30.61h-27.06c-5.58,0-10.4,3.91-11.54,9.38Z" fill="#fff"/>
        <path d="m380.38,201.28l-6.57,31.5h-38.45c-7.26,0-13.52,5.09-15.01,12.2l-17.4,83.34h-37.36l20.6-98.65c3.45-16.53,18.03-28.38,34.92-28.38h59.27Z" fill="#fff"/>
        <path d="m686.06,232.78l-11.15,53.4c-1.06,5.05,2.8,9.8,7.97,9.8h28.71l-6.75,32.34h-42.24c-17.55,0-30.66-16.13-27.08-33.31l12.99-62.22h-16.45l6.57-31.5h16.46l6.78-32.46h37.54l-6.78,32.46h37.37l-6.57,31.5h-37.37Z" fill="#fff"/>
        <path d="m484.32,201.29h-81.93l-6.57,31.5h70.34c4.74,0,8.29,4.36,7.31,9.01l-1.81,8.66h-62.56c-16.08,0-29.96,11.28-33.24,27.02l-4.04,19.31c-3.39,16.27,9.02,31.54,25.63,31.54h94.49l19.54-93.6c3.6-17.24-9.56-33.43-27.18-33.43Zm-22.43,96.01h-45c-4.58,0-8.01-4.22-7.07-8.71l.59-2.83c1.09-5.22,5.69-8.96,11.03-8.96h44.74l-4.28,20.5Z" fill="#fff"/>
      </g>
      <g>
        <polygon points="924.88 159.26 889.59 328.32 850.82 328.32 864.85 261.12 795.09 261.12 781.06 328.32 742.31 328.32 777.6 159.26 816.36 159.26 802.36 226.31 872.13 226.31 886.13 159.26 924.88 159.26" fill={`url(#${uid}-linear-gradient)`}/>
        <path d="m1058.65,159.26h-71.3c-21.18,0-39.46,14.86-43.79,35.59l-19.82,94.95c-4.15,19.86,11.02,38.53,31.31,38.53h67.43l10.77,20.31h37.89l-16.86-27.85c8.55-5.95,14.83-15.05,17.09-25.85l.17-.79,19.77-94.69c4.33-20.73-11.49-40.19-32.67-40.19Zm-6.56,45.38l-17.47,83.64-11.71-19.34h-31.92l13.37,25.2h-30.88c-6.15,0-10.76-5.66-9.49-11.68l16.24-77.79c1.42-6.81,7.42-11.69,14.38-11.69h48c6.14,0,10.74,5.65,9.49,11.67Z" fill={`url(#${uid}-linear-gradient-2)`}/>
      </g>
    </svg>
  );
}
