// GENERATED by scripts/generate-brand-components.mjs — do not edit by hand.
// Accent colours reference --color-league-accent, which falls back to the
// product accent, so this renders correctly inside and outside a league.
import { useId } from "react";

interface Props {
  className?: string;
  title?: string;
}

export default function DraftHQMark({ className = "h-24 w-auto", title = "DraftHQ" }: Props) {
  const uid = useId().replace(/:/g, "");
  return (
    <svg className={className} role="img" aria-label={title} id={`${uid}-Layer_1`} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 1200">
      <defs>
        <linearGradient id={`${uid}-linear-gradient`} x1="621.02" y1="403.95" x2="621.02" y2="1030.31" gradientUnits="userSpaceOnUse">
          <stop offset="0" stopColor="var(--color-league-accent)"/>
          <stop offset="1" stopColor="var(--color-league-accent-border)"/>
        </linearGradient>
        <linearGradient id={`${uid}-linear-gradient-2`} x1="600" y1="226.54" x2="600" y2="456.31" gradientUnits="userSpaceOnUse">
          <stop offset=".03" stopColor="var(--color-league-accent)"/>
          <stop offset=".14" stopColor="color-mix(in srgb, var(--color-league-accent) 88%, var(--color-league-accent-border))"/>
          <stop offset=".72" stopColor="color-mix(in srgb, var(--color-league-accent) 32%, var(--color-league-accent-border))"/>
          <stop offset="1" stopColor="var(--color-league-accent-border)"/>
        </linearGradient>
      </defs>
      <g>
        <path d="m552.87,712.92l-101.73,117.51h-42.76c-20.69,0-37.1-11.32-45.94-29.46-.9-2.86-1.7-5.76-2.4-8.69-.22-.94-.43-1.89-.63-2.83-.12-.53-.23-1.06-.33-1.59-.13-.63-.25-1.27-.37-1.9-.16-.86-.31-1.72-.45-2.58-.08-.49-.16-.97-.24-1.47-.36-2.41-.67-4.84-.92-7.32-.09-.81-.16-1.64-.23-2.46-.08-.88-.15-1.78-.2-2.68-.07-.95-.13-1.92-.17-2.88-.04-.82-.08-1.66-.11-2.49-.02-.67-.04-1.34-.05-2.01-.02-.57-.03-1.14-.03-1.71-.01-.78-.02-1.57-.02-2.36v-257.12h103.9v212.05h92.7Z" fill="#fff"/>
        <path d="m742.43,377.17c25.05,14.94,41.04,39.6,47.73,60.72h25.63v237.95c0,103.03-43.27,144.31-85.11,181.31-41.84,37-131.59,115.69-131.59,115.69,0,0-118.7-109.42-134.52-124.51-5.62-5.37-10.06-11.12-13.42-17.9h-42.75c-20.68,0-37.07-11.3-45.93-29.42.24.74.47,1.49.72,2.23.78,2.33,1.65,4.66,2.58,6.96.27.66.53,1.33.83,1.99.31.74.63,1.48.97,2.2.27.6.53,1.21.81,1.8.75,1.61,1.53,3.19,2.36,4.78.37.72.75,1.45,1.14,2.17.25.44.49.9.74,1.34.18.32.37.66.56.99.44.78.89,1.55,1.36,2.32.31.55.63,1.08.94,1.61,1.68,2.73,3.47,5.46,5.38,8.19.28.4.56.8.86,1.19,1.2,1.68,2.46,3.38,3.76,5.06.4.53.8,1.05,1.21,1.55,5.96,7.57,12.88,15.12,20.83,22.82.74.72,1.5,1.45,2.27,2.18l189.29,179.87,198.42-170.9c52.15-44.92,82.07-110.17,82.07-179.01v-323.19h-137.14Zm-68.88,209.64v50.26c0,47.65-45.51,75.86-86.27,75.86h-9.68l-101.16,116.83h93.5c104.92,0,210.99-70.1,210.99-197.91v-148.68l-107.38,103.64Z" fill={`url(#${uid}-linear-gradient)`}/>
        <path d="m780.94,474.74v7.12h-122.08c-3.11-6.65-11.83-14.94-35.48-14.94h-257.91l-45.03-89.73h358.13c66.47,0,102.38,52.07,102.38,97.56Z" fill="#fff"/>
      </g>
      <polygon points="594.84 851.25 603.86 879.02 633.07 879.02 609.44 896.19 618.47 923.96 594.84 906.8 571.22 923.96 580.24 896.19 556.62 879.02 585.82 879.02 594.84 851.25" fill="#fff"/>
      <polygon points="799.6 236.93 772.29 297.06 768.14 301.46 745.69 352.69 454.32 352.69 431.86 301.46 427.71 297.06 400.4 236.93 478.96 262.25 473.47 280.46 490.67 295.32 542.65 295.32 559.98 269.85 541.19 245.58 600 149.74 658.82 245.58 640.02 269.85 657.35 295.32 709.33 295.32 726.53 280.46 721.05 262.25 799.6 236.93" fill={`url(#${uid}-linear-gradient-2)`}/>
    </svg>
  );
}
