-- Cache bucket for AI announcer clips generated by /api/announcer/speak.
-- Clips are keyed by hash(persona + text) so identical announcements are
-- generated once and reused across drafts.
--
-- Writes happen exclusively through the service role (which bypasses RLS),
-- so no insert/update/delete policies are granted to users.

insert into storage.buckets (id, name, public)
values ('announcer-clips', 'announcer-clips', true)
on conflict (id) do nothing;

drop policy if exists "announcer clips public read" on storage.objects;
create policy "announcer clips public read"
  on storage.objects for select
  using (bucket_id = 'announcer-clips');
